CREATE USER foo;
CREATE DATABASE todo_app_db;
\c todo_app_db;
GRANT ALL PRIVILEGES ON DATABASE todo_app_db TO foo;
CREATE TABLE IF NOT EXISTS todos (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_DATE,
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE NULL
);
